services:
  peculiarcardgame-backend-mssql:
    container_name: peculiarcardgame-backend-mssql
    image: mcr.microsoft.com/mssql/server
    ports:
      - "11433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD
